### ISSUE TITLE
cameo_members return empty array

### ISSUE THREAD

**Issue by GSculerlor** [MagiCircles/BanGDream#115]
Example: 
[bandory.party page](https://bandori.party/card/906/Tomoe-Udagawa-Happy-Eternal-Sunset/) and [API link](https://bandori.party/api/cards/906/)

Here, there are 2 cameo members listed
![Cameo member list](https://gsculerlor.s-ul.eu/LSXTiGoP)
But in the API it return empty array
![Cameo return empty array](https://gsculerlor.s-ul.eu/Daw8EuAC)

**Comment by summertriangle-dev** [comment]
they should all be back as of a couple days ago - please reopen this if they disappear again.
