### ISSUE TITLE
Duplicating Cards From Limited Search

### ISSUE THREAD

**Issue by LatidoReMe** [MagiCircles/BanGDream#124]
Cards with the id of 807-801 are duplicating with the limited gacha filter on the cards page
![example pic](https://cdn.discordapp.com/attachments/340979523732635649/467453697966735380/chrome_2018-07-13_16-13-13.png)

**Comment by db0company** [comment]
https://github.com/MagiCircles/BanGDream/commit/595e7a6422652857d15283221663b19cdfe74ed2
and https://github.com/MagiCircles/MagiCircles/commit/8ec84ba9746de934a65a13e08fd0814a769165ca
