### ISSUE TITLE
Make Status Filter for Gacha Include Reruns

### ISSUE THREAD

**Issue by LatidoReMe** [MagiCircles/BanGDream#137]
Natsuzora has a rerun on our site in the future
![image](https://user-images.githubusercontent.com/30684769/44564291-16003980-a717-11e8-968c-c39ac0e3f966.png)

But this is all I get when I look into the future on JP
![image](https://user-images.githubusercontent.com/30684769/44564187-92dee380-a716-11e8-9cf2-1edb7f66bb25.png)

Since reruns don't happen that often it ain't super bad, but we should still try to make reruns findable this way.

**Comment by db0company** [comment]
I don't think this has been fixed?
