### ISSUE TITLE
member's page: order by band as default, instead of popularity

### ISSUE THREAD

**Issue by shinylyni** [MagiCircles/BanGDream#14]

**Comment by violet-r** [comment]
Set up like Sukutomo with the chibis fixed at a smaller image resolution and the band's logo, possibly?

**Comment by shinylyni** [comment]
I think that's what they wanted, yeah

**Comment by db0company** [comment]
I can't add the logos or anything else between elements of the list, and I can't have 5 per line (only 1, 2, 3, 4, 6, 12).

**Comment by violet-r** [comment]
Very Unfortunate :(
I think we should ask the community, otherwise I'd rather leave it as it is.

**Comment by AmbiBambii** [comment]
I personally I have no opinion as to how we sort the members. The most unbiased we can be is to sort is in alphabetical order. While band order sounds nice, how do we choose which band goes first?

**Comment by shinylyni** [comment]
@Ambi the official order in-game (based on character IDs) is PoPiPa, Afterglow, HHW, PasuPare, Roselia

**Comment by summertriangle-dev** [comment]
sorting by band would be the most useful choice. i think most people go to that page to find a specific character, and having a well-defined order would make that easier.

and adding to shiny's comment above: the game prefers popipa, afuro, paspare, roselia, HHW in menus.

**Comment by Zyobop** [comment]
I think the (PPP, aglo, p*p, roselia, hhw) band order would be the most fitting ^^

**Comment by LatidoReMe** [comment]
The band order is the most logical, however I think the actual best order would be a combination of band and instrument, that way it directly replicates the game's natural ordering. However, we don't have an instrument type field that can easily be sorted (we manually input each item, and didn't give them an overall type) so without an extra field, this would not work cleanly.
