### ISSUE TITLE
Replace Stamp Fields With Foreign Key To Stamp Assets

### ISSUE THREAD

**Issue by LatidoReMe** [MagiCircles/BanGDream#142]
Pretty Self-Explanatory. Title would function the same as Stamp Translation, and each image would be displayed under their proper version.

Would reduce images uploaded in the future & duplication of inputted info, so good all around. Most difficult thing would probably be configuring it to work with our special event magicollection/js code.

**Comment by db0company** [comment]
I believe this is done, right? Feel free to re-open if not.
