### ISSUE TITLE
Add Event/Other Field to Stamps

### ISSUE THREAD

**Issue by LatidoReMe** [MagiCircles/BanGDream#143]
The naming of the field & values would have to be decided, but it'd be good for:
+ Finding default stamps & special occasions stamps (like the TW new years ones)
+ Minimizing the query from https://github.com/MagiCircles/BanGDream/issues/142 (Makes it easier for database maintainers to find the stamp they need!)

My knowledge on types is minimal but the field & filter itself should not be hard to implement. I would suggest styling the field similar to:
![image](https://user-images.githubusercontent.com/30684769/44961504-ff03d900-aec6-11e8-9ff3-2f6d3b96d582.png)
But a Only/None field for Event could work well too.

**Comment by db0company** [comment]
I'm not sure I get exactly what would be the final result of this, or if it's even still needed anymore with the stamps being in the assets gallery.

@LatidoReMe Do you mind explaining a bit more?

**Comment by LatidoReMe** [comment]
We ended up having stamps link themselves to events instead of events fetching each stamp, so the query thing isn't as relevent anymore I believe.

You recently ended up adding an event yes/no field to stamps that achieves the goal of the filter I was wanting, so this is actually done!
