### ISSUE TITLE
No Icon for Member Source

### ISSUE THREAD

**Issue by LatidoReMe** [MagiCircles/BanGDream#158]
It ain't too important, but the Source for Members has no icon.
![image](https://user-images.githubusercontent.com/30684769/45787542-bec48a80-bc2a-11e8-97ea-821c6ed2a860.png)

The fix for this should be pretty simple too
_just add the icon for it here:_ https://github.com/MagiCircles/BanGDream/blob/5942870d6e17ce179636a1c99792496d7ba0f5d4/bang/magicollections.py#L274

**Comment by db0company** [comment]
I actually left it like that on purpose because I think it's a less important detail so the line is a bit smaller.
