### ISSUE TITLE
Alternate Song Cover Images

### ISSUE THREAD

**Issue by violet-r** [MagiCircles/BanGDream#198]
Korean Server does alternate cover art for their songs, and sometimes cover art gets swapped out. I would like to group song images together some how like the card galleries at the bottom.

Alternative Covers: [img KR] [img OLD]

as an example if it makes sense.

**Comment by LatidoReMe** [comment]
For this, would you prefer for us to utilize the current Album cover tag in Official Art, or to just create a couple new fields in song?

We could query Assets connected to the song with the Album Cover (or even w/o the tag, if you wanted) and then display their images or thumbnails in a field, with links to each item for high-res.

OR we can just create a korean_image + old_image field for each song, and display the two images together in a single field. It'd be simpler, but less flexible than the gallery option.

**Comment by violet-r** [comment]
Query sounds the best since we already have it all stored, except for KR covers.

**Comment by LatidoReMe** [comment]
Okie-dokes! And would you want the query to be for just assets connected to the song, or just official art tagged with Album cover?
