### ISSUE TITLE
Edit favorite cards from list under profile

### ISSUE THREAD

**Issue by violet-r** [MagiCircles/BanGDream#28]
Possibility of deleting cards from “favorite cards” tab with ease? Similar to how you can edit cards quickly in the doc, like this
![likethis](https://user-images.githubusercontent.com/26831031/36363800-9f66dc3c-1505-11e8-99c3-b987b83f85b4.PNG)

**Comment by db0company** [comment]
Implemented but doesn't disappear after delete yet. Will be done as part of this: https://github.com/MagiCircles/MagiCircles/issues/38
