### ISSUE TITLE
Profile Center Art Options

### ISSUE THREAD

**Issue by violet-r** [MagiCircles/BanGDream#31]
Selecting a center only allows you to pick trained art for the profile splash image if you have selected it 'trained'. Not an issue for untrained only allowing untrained art, but not quite fair for people with trained cards to only have the option of trained art on their profile.

**Comment by db0company** [comment]
Just a "show trained center" checkbox when editing profile?
Or you want the equivalent of Sukutomo for each card? (see below)

<img width="652" alt="screen shot 2018-02-19 at 2 09 38 pm" src="https://user-images.githubusercontent.com/722281/36364299-4bfbcebc-157e-11e8-9b13-b0f79c1d4f67.png">

**Comment by violet-r** [comment]
"Prefer Untrained Image" might work.
Just wanted to give people the option of picking between two arts for their profile header image ^_^
