### ISSUE TITLE
About Us Section: Add “Meet Kanae!” Introduction to mascot, her artist/designer.

### ISSUE THREAD

**Issue by violet-r** [MagiCircles/BanGDream#32]

**Comment by db0company** [comment]
Can you write the exact text you want there?

**Comment by violet-r** [comment]
# Meet Our Mascot, Kanae the Bandoroid!

**Who's Kanae?** She keeps our databases correct, helps manage your idols, and is our Mascot for Bandori.Party! An android who collects data about Bang Dream and it's cast of gals, she always has her tablet on hand to update any new information that might come in. **How was she born?** We thought it would be neat to have a contest where we had someone in the community embody the site & it's functions, and they delivered! Kanae was born from the design ideas of (NeroMao)[https://bandori.party/user/2452/NeroMao/], polished up by (Brella)[http://umbrellaguns.tumblr.com/], and named by the community! Kanae is not only our mascot, but one of our fellow staff members as well, so we hope you'll learn to love Kanae like we love her too!
