### ISSUE TITLE
Extracts Gallery

### ISSUE THREAD

**Issue by violet-r** [MagiCircles/BanGDream#36]
Deposit backgrounds/host background images on the site as a gallery and maybe other misc. extracts?

**Comment by db0company** [comment]
Didn't you guys say you wanted it in the wiki instead?

**Comment by violet-r** [comment]
I didn't know Lati/Ambi had picked that, but personally I would like to see an image gallery on site. Easier for management of multiple dataminers to post the images directly to the site as opposed to an imgur gallery that can be spread around and lose it's attribution to the Bandori.Party site.

Display images in a table-format. Click to open in another tab.

**Comment by db0company** [comment]
Sounds good.

@summertriangle-dev @shinylyni  is that something that could potentially be automated via an API endpoint whenever new assets get added?

**Comment by summertriangle-dev** [comment]
potentially, yes
