### ISSUE TITLE
Clicking +(X) Cards - View All Pops open a new window

### ISSUE THREAD

**Issue by violet-r** [MagiCircles/BanGDream#40]
Should expand to show the rest of the cards like SIT instead of a new window?

**Comment by db0company** [comment]
It's gonna stay like that, that's how it's done from MagiCircles.

The idea is that at some point when you have a lot of cards it's pointless to just see a huge list. So when you have more than X, then it opens in a new tab which also lets you filter and do more things to see your cards, such as ordering by something else, filtering by rarity, etc.
