### ISSUE TITLE
Version Gacha Filtering Fix

### ISSUE THREAD

**Issue by LatidoReMe** [MagiCircles/BanGDream#53]
When filtering through gachas via versions, gachas will not appear unless [Version] version - image is specified. Since we're already not using the banners of other versions for displaying banners, it should default to the JP version's image for proper displaying. 
[Link to example of bug](https://imgur.com/a/kuN3e)

**Comment by db0company** [comment]
@LatidoReMe @violet-r 

We had that discussion when we launched versions and you asked for checking using date and not image:

<img width="928" alt="screen shot 2018-05-04 at 8 07 51 am" src="https://user-images.githubusercontent.com/722281/39608155-1c2b64ee-4f72-11e8-9b6b-6981e2121a1d.png">

**Comment by LatidoReMe** [comment]
I think this was before you implemented some more version-specific things, so it might already be fixed? Most of the stuff for servers are up currently and there are none with dates and not images rn that I know of, so I don't have a chance to see if it still occurs.

I did want it to be checked by date, and if it is doing that as well as displaying even without its own version banner, then it is good.
