### ISSUE TITLE
Event cards don't show up as event cards in /cards

### ISSUE THREAD

**Issue by AmbiBambii** [MagiCircles/BanGDream#66]
In https://bandori.party/events, you can see which cards are the event cards. However, under https://bandori.party/cards, even if you sort them by "event only", new event cards won't show up. Possible issue could be because of what happened with Michelle Party, but just a random thought

**Comment by db0company** [comment]
Closed with https://github.com/MagiCircles/BanGDream/commit/159ed3126ee694d0d2370af78c273a3e79022178
