### ISSUE TITLE
text bleeding on mobile

### ISSUE THREAD

**Issue by shinylyni** [MagiCircles/BanGDream#7]
When you click on a Member when on a mobile phone (or at least Samsung Galaxy S7 with Android) the member info that pops up does not scale to fit screen size; instead, the text runs off the page and off screen. Examples: http://imgur.com/a/yIWJA

**Comment by violet-r** [comment]
Profile looks awful on mobile; icons for cards needs to be resized + banner area needs to be adjusted.
