### ISSUE TITLE
Pop-up to ToS for first-time posters

### ISSUE THREAD

**Issue by LatidoReMe** [MagiCircles/BanGDream#77]
Have a text-box pop up with a reminder to read the site's [Rules on Posting Activities](https://bandori.party/wiki/Rules%20on%20Posting%20Activities) before making their first activity.

**Comment by db0company** [comment]
We show the rules everywhere now and so far people seem to be aware of them, so I don't think we need this feature. Feel free to re-open if you still want it though.
