### ISSUE TITLE
Bump activities based on reputation

### ISSUE THREAD

**Issue by db0company** [MagiCircles/BanGDream#81]
Reputation: users get reputation points when they're active, and this score can determine the impact of their like: only users with certain reputation will "bump" the post when they like, otherwise will not bump (like still counts)

TODO: determine what should give you reputation points.

Ideas:

- when you add a card, event participation, played song, etc: 1 point
- when you like an activity: 1 point
- when someone likes your activity: 3 points
- when you post an activity: 5 points
- when you follow someone: 4 points
- when someone follows you: 5 points

Let the reputation thingy run for a while, adapt points if needed, and once we have a good amount of points we can determine what's the threshold to consider someone good enough to "bump" activities.

Why do this?

This comes directly from issues we have with sukutomo users unliking/liking to bump their thing, flooding the feed, etc. The quick and dirty solution we implemented is just to not allow unlike, but then another issue was that they create dummy account to bump. By limiting bumps to users we trust thanks to an auto reputation, we ensure the feed really corresponds to good content that got updated / liked recently.

**Comment by violet-r** [comment]
I think this is a good middle ground for posts, of course we should have "Most Recent" and this will replace current popular module?

**Comment by LatidoReMe** [comment]
I think having a most recent alongside a new Popular module would be pretty cool, especially if moderators wanna check for any bad activities. Besides, it is good to be able to escape the same posts over and over again, so if we could add in a Most Recent, I'd be all for that.

Alongside the rep point stacking thing, I was gonna ask if there was a way for posts' popularity to get deprecated over time? Like, I know the idea is that they'll just stop liking it if it's old, but new users not looking at post dates might keep on liking old things again and again, so having a failsafe like that would be nice imo.

Also, I don't know if following someone and liking posts are good ways to build up rep. Unless we limit the amount of rep you can get at a time from these actions, I feel like following people/liking others' posts are super easy to manipulate. I would comment more on the rep point values, but without knowing what the base "reputable" is, I can't say rather they're too extreme or not.

**Comment by AmbiBambii** [comment]
I feel like this isn't the most efficient way to settle this (but not like I have any other better propositions LOL). I can see how this can be helpful, especially on Sukutomo. However, I don't thinking building up a reputation is the best way to go around this - like Latido said, repping can be easily manipulated (i.e. creating dummy accounts to promote your own posts will also add manipulated points to the user). 

I'd like to tag along with what Violet says about having a "Most Recent" tab. A problem I noticed is that many new posts get bumped so they show up in the beginning of the "New" tab on Sukutomo, so if we were to implement that on BanPa then I would like to keep it sorted by date exclusive and make it impossible to "bump" new posts to the top of the "New" tab (if possible).

**Comment by Zyobop** [comment]
(I Basically just agree with everything Latido said) getting rep points from actions that you do (following, liking someone) feels like it would be abused too much, and as said, that a new/recent tab would be great, where reputation has no effect on the displayed posts on the recent tab, for new members to get out there without being overshadowed.

**Comment by db0company** [comment]
Tabs are already planned and confirmed, so if you want to discuss them please use the right issue (https://github.com/MagiCircles/BanGDream/issues/74) and use this one only for discussions about reputation points. Also note that the option to sort by creation date is already up.

I understand the concerns about the abuse of reputation points and that's why I would like your input on exactly what you think should give reputation points.

You might also want to know that reputation points will be completely hidden from the users, who will also not be aware of whether or not posts get bumped when they like. Basically we want to limit abuse by having the algorithm for the default ordering opaque. It will not prevent people from reading the code to understand it, but it would reduce that potential problem to a small enough amount of people we could deal with manually.

Regarding old activities, it's also planned to allow users to "archive" their own activities or auto archive them after a certain date to prevent bump. You can see the details and all the rest of the plan in the staff announcement channel (circles survey results) + my personal planning https://github.com/MagiCircles/Circles/wiki/Planning

**Comment by db0company** [comment]
Sorry my first message was a bit vague 🙇

**Comment by AmbiBambii** [comment]
It's all good :) 

Would it be possible to allow points to only be considered by users who fit a certain criteria? I.e. account has existed for 2 weeks/made x number of posts, etc. I feel like that could help fix an issue of the reputation points being manipulated.
