### ISSUE TITLE
Wiki Home page states no longer correct available regions

### ISSUE THREAD

**Issue by Stekeblad** [MagiCircles/BanGDream#87]
The Wiki Home Page (https://github.com/MagiCircles/BanGDream/wiki) says 

"The game is currently only available in the Japan, Korean, and Taiwanese regions" 

but since April 4th the app is available world wide (https://bang-dream-gbp-en.bushiroad.com/news/now-available-worldwide.php)

**Comment by LatidoReMe** [comment]
Thank you for bringing this up! We've updated the wiki to be more accurate now.
