### ISSUE TITLE
Activities buttons to bump, drown, tag as staff picks, archive, ghost archive

### ISSUE THREAD

**Issue by db0company** [MagiCircles/BanGDream#93]
- Bump (staff only): will bump the activity regardless of whether or not you liked it
- Drown (staff only): basically the opposite of bump, will move it 24h down in the queue
- Tag as staff pick (staff only): will have a little crown icon showing staff liked it + will show up in staff picks tab
    - I will also add a little flame icon that show up when activities reach 70 likes with the caption "popular"
- Archive (user only): will only show up for author of the activity and will prevent any bump in the future, and will have a little archive box icon showing the user archived it
- Ghost archive (staff only): will prevent any bump in the future but the user who created the activity and all the other users will not know about it (this is to prevent discourse to show up first and encourage other users to join in the discourse)

This is the 2nd most asked feature from the staff features circles survey. You can see the full survey results in the pinned message of #staff_announcements

**Comment by db0company** [comment]
Should the archive button prevent likes, bumps, or both?

In other words, when a user archives their activity, should other users still be able to like? If we go for Reddit-like, then they shouldn't be able to like. But we can also decide to allow users to like, just prevent bumps. Let me know what you think.

**Comment by LatidoReMe** [comment]
If possible I think that old posts should still be likable! While I don't think many people focus on how many likes their posts got, I'm sure a few would like to know what the rest of the community actually liked the best even from way back when. Ghost archiving is another valid reason too, so I think we should keep likes on post-archive.

**Comment by rdsathene** [comment]
This seems like a really good selection.
